#' Global storage for Newapp
#' 
#' Stores data for use in Newapp
#' 
#' This file is the storage unit for the shiny app Newapp. There is also a
#' function here called \code{get_program_chan} which finds out which channel a
#' certain programme is broadcast on.
#' 
#' @param program_name The character name of a radio programme
#'   
#' @param pro A dataframe generated by the Lab 5 package function
#'   \code{get_programs}.
#'   
#' @return channel_name The character name of the radio channel upon which
#'   \code{program_name} is broadcast.
#'   
chan <- as.character(read.csv("data/channels.csv",fileEncoding = "UTF-8")[,1])

son <- as.character(read.csv("data/song.csv",fileEncoding = "UTF-8")[,1])
pro <- read.csv("data/programs.csv",fileEncoding = "UTF-8")

get_program_chan <- function(program_name,pro){
  
  for(i in 1:length(pro[,1])){
    if(as.character(pro[i,1]) == as.character(program_name)){
      
      return(as.character(pro[i,3]))
    }
  }
}

